# Generated by Django 5.1.1 on 2024-10-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='account',
        ),
    ]
