# Generated by Django 5.1.1 on 2024-10-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_rename_user_comment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='problem_images/'),
        ),
    ]
