# Generated by Django 5.1.1 on 2024-10-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_comment_is_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_pinned',
        ),
    ]
