# Generated by Django 5.1.2 on 2025-07-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0027_alter_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-scheduled_post_at']},
        ),
    ]
