# Generated by Django 5.1.2 on 2025-07-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0028_alter_problem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['scheduled_post_at']},
        ),
    ]
