# Generated by Django 5.1.2 on 2025-07-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0032_alter_problem_options_remove_comment_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
