# Generated by Django 5.1.2 on 2024-10-25 05:11

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='default_profile.png', force_format=None, keep_meta=True, quality=85, scale=None, size=[256, 256], upload_to='profile_pictures/'),
        ),
    ]
