# Generated by Django 5.1.1 on 2024-10-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
