# Generated by Django 5.1.1 on 2024-10-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
