# Generated by Django 5.1.1 on 2024-10-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_remove_comment_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
