# Generated by Django 5.1.1 on 2024-10-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_problem_solution_problem_solution_post_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='scheduled_post_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
