# Generated by Django 5.1.2 on 2024-10-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_alter_comment_created_at_alter_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
