# Generated by Django 5.1.2 on 2024-10-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_alter_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
