# Generated by Django 5.1.2 on 2024-10-22 19:06

import _problems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0022_alter_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.CharField(default=_problems.models.generate_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
