# Generated by Django 5.1.2 on 2024-10-23 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0023_alter_problem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='id',
            new_name='unique_id',
        ),
    ]
