# Generated by Django 5.1.2 on 2024-10-23 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0024_rename_id_problem_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='unique_id',
            new_name='id',
        ),
    ]
