# Generated by Django 5.1.2 on 2025-04-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0025_rename_unique_id_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
