# Generated by Django 5.1.2 on 2025-04-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0026_alter_problem_content_alter_problem_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=100000),
        ),
    ]
