# Generated by Django 5.1.2 on 2025-07-13 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0029_alter_problem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={},
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_as_solution', to='problems.comment'),
        ),
    ]
