# Generated by Django 5.1.2 on 2025-07-13 02:13

from django.db import migrations

def transfer_pinned_to_foreign_key(apps, schema_editor):
    """
    This function finds every comment with pinned=True and sets the corresponding
    problem's new solution_comment field to point to that comment.
    """
    # It's best practice to use apps.get_model to get the historical version of models.
    Comment = apps.get_model('problems', 'Comment')

    # We only need to loop through the comments that were pinned.
    for pinned_comment in Comment.objects.filter(pinned=True):
        problem = pinned_comment.problem
        problem.solution_comment = pinned_comment
        problem.save(update_fields=['solution_comment'])

def reverse_data_transfer(apps, schema_editor):
    """
    This function allows you to reverse the migration if needed.
    It finds problems with a solution_comment and sets the corresponding
    comment's pinned field back to True.
    """
    Problem = apps.get_model('problems', 'Problem')

    for problem in Problem.objects.filter(solution_comment__isnull=False):
        solution = problem.solution_comment
        if solution:
            solution.pinned = True
            solution.save(update_fields=['pinned'])

class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0030_alter_problem_options_problem_solution_comment'), # The migration file from Phase 1
    ]

    operations = [
        migrations.RunPython(transfer_pinned_to_foreign_key, reverse_code=reverse_data_transfer),
    ]