# Generated by Django 5.1.2 on 2025-07-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0031_transfer_pinned_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['scheduled_post_at']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pinned',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solution',
        ),
    ]
