# Generated by Django 6.1.1 on 2026-09-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0033_alter_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-scheduled_post_at']},
        ),
    ]
