# Generated by Django 5.1.2 on 2024-10-21 07:14

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='default_profile.png', force_format=None, keep_meta=True, quality=85, scale=None, size=[128, 128], upload_to='profile_pictures/'),
        ),
    ]
