# Generated by Django 5.1.2 on 2025-03-24 08:43

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='profile_pictures/default_profile.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[256, 256], upload_to='profile_pictures/'),
        ),
    ]
